# Project information
site_name: Geotribu
site_description: Veille libre sur la géomatique
site_author: Geotribu
site_url: https://geotribu.github.io/website/
copyright: '&#127279; geotribu'

# Repository
repo_name: 'geotribu/website'
repo_url: 'https://github.com/geotribu/website'

# advanced options
docs_dir: '../../content'
site_dir: '../../build/mkdocs/site'

# Plugins
plugins:
  - awesome-pages
  - git-authors
  - git-revision-date-localized:
      ignore_missing_git: true
      type: datetime
  - minify:
      minify_html: true
  - search:
      lang: fr
      prebuild_index: python

# Theme
theme:
  name: 'material'
  custom_dir: '../../content/theme/'
  feature:
    tabs: true
  font: false
  language: 'fr'
  palette:
    primary: 'teal'
    accent: 'deep-orange'
  favicon: 'assets/images/geotribu/logo_geotribu.png'
  logo: 'assets/images/geotribu/logo_geotribu.png'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/geotribu/'
    - type: 'twitter'
      link: 'https://twitter.com/geotribu/'

# Extensions to enhance markdown - see: https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - attr_list
  # Admonition - https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  # CodeHilite - https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
  - codehilite:
      linenums: true
  # Metadata - https://squidfunk.github.io/mkdocs-material/extensions/metadata
  - meta
  # PyMdown extensions - https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.superfences
  # Permalinks - https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
  - toc:
      permalink: true

# Navigation - Menu organization
# # Disabled to use auto detection
# nav:
#   - Accueil: index.md
