# Project information
site_name: Geotribu
site_description: Veille libre sur la géomatique
site_author: Geotribu
site_url: https://geotribu.github.io/website/
copyright: '&#127279; geotribu'

# Repository
repo_name: 'geotribu/website'
repo_url: 'https://github.com/geotribu/website'
edit_uri: 'edit/master/content'

# Custom folder structure
docs_dir: '../../content'
site_dir: '../../build/mkdocs/site'

# Plugins
plugins:
  - awesome-pages
  - git-authors:
      show_contribution: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - minify:
      minify_html: true
  - search:
      lang:
        - en
        - fr
      prebuild_index: true
      separator: '[\s\-\.]+'

# Theme
theme:
  name: 'material'
  custom_dir: '../../content/theme/'
  favicon: 'assets/images/geotribu/logo_geotribu.png'

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - tabs
    - instant
  font: false
  language: 'fr'
  logo: 'theme/assets/images/geotribu/logo_geotribu.png'
  palette:
    primary: 'teal'
    accent: 'deep-orange'

# Integrations with 3rd party
google_analytics:
  - 'UA-162113930-1'
  - 'auto'

# Customization
extra:
  disqus: 'geotribu-static'  # comment system
  manifest: 'manifest.webmanifest'  # PWA declaration
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/geotribu/'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/geotribu/'

extra_css:
  - 'theme/assets/stylesheets/extra.css'

# Extensions to enhance markdown - see: https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - attr_list
  # Admonition - https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  # CodeHilite - https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
  - codehilite:
      linenums: true
  # Metadata - https://squidfunk.github.io/mkdocs-material/extensions/metadata
  - meta
  # PyMdown extensions - https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.superfences
  # - pymdownx.tabbed  # to be enabled in the furture with PyMarkdown >= 7
  # Permalinks - https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
  - toc:
      permalink: true

# Navigation - Menu organization
# # Disabled to use auto detection
# nav:
#   - Accueil: index.md
