ci-cd:
    - .github/**/*

dependencies:
    - ./**/requirements.txt

mkdocs:
    - src/mkdocs/**/*
    - content/**/*.pages
    - content/manifest.webmanifest

rdp:
    - content/rdp/**/*.md

thème:
    - content/theme/**/*

tuto:
    - content/tutoriels/**/*.md
