name: Markdown Linter

# Trigger
on:
  pull_request:
    branches: [ master ]
    paths:
      - "content/**/*.md"

jobs:
    lint-markdown:
      name: Lint markdown files
      runs-on: ubuntu-latest

      steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '12'

      - name: Check out code
        uses: actions/checkout@v2

      - name: List files changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ' '

      - name: Install markdown-cli
        run: yarn add markdownlint-cli --dev --non-interactive --no-lockfile --prefer-offline

      - name: Run markdownlint-cli on new files
        id: mdl_added
        run: yarn markdownlint -i "**/template_*.md" -o "markdown-lint-report-added.txt" ${{ steps.file_changes.outputs.files_added }}
        continue-on-error: true

      - name: Run markdownlint-cli on modified files
        id: mdl_modified
        run: yarn markdownlint -i "**/template_*.md" -o "markdown-lint-report-modified.txt" ${{ steps.file_changes.outputs.files_modified }}
        continue-on-error: true

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: markdown-lint-report
          path: |
            markdown-lint-report-added.txt
            markdown-lint-report-modified.txt

      - name: Comment PR
        if: steps.mdl_added.failure()
        uses: mshick/add-pr-comment@v1
        with:
          message: |
           **Hello MASTER**
          allow-repeats: false

