name: Markdown Linter

# Trigger
on:
  pull_request:
    branches: [ master ]
    # paths:
    #   - "content/**/*.md"

jobs:
    lint-markdown:
      name: Lint markdown files
      runs-on: ubuntu-latest

      steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '12'

      - name: Check out code
        uses: actions/checkout@v2

      # - name: Get modified files in the commit
      #   run: git diff-tree --no-commit-id --name-only -r $GITHUB_SHA

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3

      - name: show off
        run: |
          echo '${{ steps.file_changes.outputs.files_modified}}'

      - name: Install markdown-cli
        run: yarn add markdownlint-cli --dev --non-interactive --no-lockfile --prefer-offline

      - name: Run markdownlint-cli
        run: yarn markdownlint -c .markdownlint.json -i "content/**/template_*.md" -o "markdown-lint-report.txt" "content/**/*.md"
        continue-on-error: true

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: markdown-lint-report.txt
          path: markdown-lint-report.txt
